# Generated by Django 4.2.28 on 2026-03-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('wishlist', 'Wishlist'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('ghosted', 'Ghosted'), ('follow_up', 'Follow Up')], default='Applied', max_length=20),
        ),
    ]
