# Generated by Django 4.2.28 on 2026-03-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('Human Resources', 'Human Resources'), ('Design Interview', 'Design Interview'), ('Technical Interview', 'Technical Interview'), ('Technical Hands On', 'Technical Hands On'), ('Final', 'Final')], max_length=50),
        ),
    ]
